// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2vXIDlJ1BApAUJyTFCHPjxoZkDmLaArg',
    appId: '1:925342257889:web:fa832efa2c859d5ddedda0',
    messagingSenderId: '925342257889',
    projectId: 'todolistapp-4428e',
    authDomain: 'todolistapp-4428e.firebaseapp.com',
    storageBucket: 'todolistapp-4428e.firebasestorage.app',
    measurementId: 'G-3DHCKPM8VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKeY8nhhBPo-Zqq4xwKsMWwJTPOmdOmc',
    appId: '1:925342257889:android:0fe39faeb782220bdedda0',
    messagingSenderId: '925342257889',
    projectId: 'todolistapp-4428e',
    storageBucket: 'todolistapp-4428e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhvUrLZVlpQ8oVfhnSyWWuJKuJ5kawimc',
    appId: '1:925342257889:ios:2677ae4accfdb23ededda0',
    messagingSenderId: '925342257889',
    projectId: 'todolistapp-4428e',
    storageBucket: 'todolistapp-4428e.firebasestorage.app',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhvUrLZVlpQ8oVfhnSyWWuJKuJ5kawimc',
    appId: '1:925342257889:ios:2677ae4accfdb23ededda0',
    messagingSenderId: '925342257889',
    projectId: 'todolistapp-4428e',
    storageBucket: 'todolistapp-4428e.firebasestorage.app',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2vXIDlJ1BApAUJyTFCHPjxoZkDmLaArg',
    appId: '1:925342257889:web:6e7060922612614bdedda0',
    messagingSenderId: '925342257889',
    projectId: 'todolistapp-4428e',
    authDomain: 'todolistapp-4428e.firebaseapp.com',
    storageBucket: 'todolistapp-4428e.firebasestorage.app',
    measurementId: 'G-6W0EH5YKV4',
  );
}
